package it.rdm.hadoop.cooccurence;

import java.io.File;
import java.io.IOException;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.input.TextInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.mapreduce.lib.output.TextOutputFormat;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;


/**
 * Co-occorrenze
 * Input: un file testuale
 * Output: frequenza delle coppie di parole che co­occorrono su una stessa riga
 * 
 *  
 *  Pseudocode:
 * 
 * mapper(key, value){
 * 	set list(distinctWords) = {distinct words in value}
 * 	foreach (wordPair) in distinctWords:
 * 		emit(wordPair,1)
 * }
 * 
 * reducer(key, list(values)){
 * 	set count = 0
 * 	foreach value in values:
 * 		count += value
 * 	emit(key, count)
 * }
 *
 *
 * Driver class.
 */
public class Cooccurence extends Configured implements Tool {

  private static int numberOfReducers;
  private Path inputPath;
  private static Configuration conf;
  private static Path outputDir;

  @Override
  public int run(String[] args) throws Exception {

    conf = this.getConf();
    //  define new job
    Job job = new Job(conf);

    //  assign a name to the job
    job.setJobName("Ruben De March's Co-Occurence");
    
    //  set input path for the job
    FileInputFormat.addInputPath(job, inputPath);
    
    //  set output path for the job
    FileOutputFormat.setOutputPath(job, outputDir);
    
    // set the jar class
    job.setJarByClass(getClass());
    
    //  set job input format
    job.setInputFormatClass(TextInputFormat.class);
    
    //  set map class
    job.setMapperClass(CooccurenceMapper.class);
    
    //  set map output key and value classes
    job.setMapOutputKeyClass(TextCouple.class);
    job.setMapOutputValueClass(LongWritable.class);
    
    //  set reduce class
    job.setReducerClass(CooccurenceReducer.class);
    
    //  set number of reducers
    job.setNumReduceTasks(numberOfReducers);
    
    //  set reduce output key and value classes
    job.setOutputKeyClass(TextCouple.class);
    job.setOutputValueClass(LongWritable.class);
    
    //  set job output format
    job.setOutputFormatClass(TextOutputFormat.class);
    
    //  execute the job and wait for completion
    return job.waitForCompletion(true) ? 0 : 1;
  }
  
  public Cooccurence (String[] args) throws IOException {
    if (args.length != 3) {
      System.out.println("Usage: Cooccurence <num_reducers> <input_path> <output_path>");
      System.exit(0);
    }
    
    numberOfReducers = Integer.parseInt(args[0]);
    this.inputPath = new Path(args[1]);
    //Create a temporary output directory for first job, located next to final output directory.
    //Its random name contains actual time, expressed in milliseconds. 
    outputDir = new Path(args[2]+File.separator+".."+File.separator+"temp"+System.currentTimeMillis());
  }
  
  public static void main(String args[]){
	int res = 1;
    try {
		if (ToolRunner.run(new Configuration(), new Cooccurence(args), args)==0){
			//if first job succeeds, the second one will be executed
			res = ToolRunner.run(new Configuration(), new SortCooccurence(numberOfReducers, outputDir, new Path(args[2])), args);
		}
		// Remove temporary folder (generated by first job) recursively
	    outputDir.getFileSystem(conf).delete(outputDir,true);
	} catch (Exception e) {
		e.printStackTrace();
	} finally {
	    System.exit(res);
		}
  }
  
}